### ISSUE TITLE
NotCallableException when adding controller to route

### ISSUE THREAD

**Issue by dsazup** [PHP-DI/Silex-Bridge#1]
Hello, 
I've been testing this package and what I usually do in silex is I have all controllers as classes. I define my routes like this:

```
$app = new Silex\Application();
$app['debug'] = true;
$app->get('/hello/{name}', 'Test\Controller::test');
```

It works perfectly in silex, however if I add this bridge to my app

```
$app = new DI\Bridge\Silex\Application();

$app['debug'] = true;
$app->get('/hello/{name}', 'Test\Controller::test');
$app->run();
```

I get NotCallableException in CallableReflection.php line 52: Test\Controller::test is not a callable
Is there an easy way to solve this?

**Comment by mnapoli** [comment]
Ah yes PHP-DI supports this syntax for methods: `['Test\Controller', 'test']`.

This isn't perfect because in PHP `'Test\Controller::test'` is a valid callable, support for this should probably be added in PHP-DI. The reason I don't use this syntax so much is that with PHP 5.5 I can do: `[Controller::class, 'test']`.

**Comment by mnapoli** [comment]
FYI I just tagged 1.0 for this package.

**Comment by dsazup** [comment]
Thanks, looking forward to it.

**Comment by mnapoli** [comment]
I created https://github.com/PHP-DI/PHP-DI/issues/272, I'll keep track of this feature in the main repository. Thank you.

**Comment by mnapoli** [comment]
Hi, this feature was implemented in https://github.com/PHP-DI/Invoker/pull/3 you can run `composer update` and it should work!
