### ISSUE TITLE
Injecting Request into controller constructor

### ISSUE THREAD

**Issue by felixfbecker** [PHP-DI/Silex-Bridge#14]
It would be nice to inject the `Request` object into the controller constructor to do stuff that applies to all methods. It works fine for methods, but when used on the constructor the DI container creates a _new_, empty Request object (like `new Request()`) instead of injecting the current request.

**Comment by mnapoli** [comment]
Hi! This is an expected behavior: when you inject a class, PHP-DI will create an instance of that class. The request is not specific for PHP-DI when it comes to injecting it into services.

Controller parameters are different: the request, like route attributes, are specific cases for controller parameters only and are not registered in the container. They can't be injected.

This is something that we don't want to change because injecting the request in a service or a controller is considered a bad practice. If you want to read more about it I can recommend this: http://symfony.com/blog/new-in-symfony-2-4-the-request-stack and this: https://igor.io/2013/03/31/stateless-services.html

If you really want to, you still can set the current Symfony request manually in PHP-DI (`$container->set(Request::class, $theRequest)`). But I would recommend against that as it will create issues in the long run.

Hope that answers your question!

**Comment by felixfbecker** [comment]
@mnapoli Thanks for the answer. But why can the request and route params get injected into controller methods and not into the controller constructor? Lets say I have a REST API and a controller for a resource with index, post, put, delete methods. Some stuff must be done for every single of these, for example a security check for an API token. I thought this could be nicely done in the controller constructor as it gets executed before any method. When the check fails, I wanted to throw a UnauthorizedHttpException. Maybe you can tell me a better way to do it?

**Comment by mnapoli** [comment]
You can call the method that checks the authorization in every controller method? Or better, you can have security checks done before the controller is called, for example using [a middleware](http://silex.sensiolabs.org/doc/middlewares.html)?

There is a difference between injecting stuff in a constructor or passing them as parameters: state. The request as well as route parameters represent state of the current request. In stateless objects (like services, controllers, etc.) state should not be stored in the object (in properties). For example that would break if the controller was going to be called again in the same process (for a sub-request). So there is no point in passing state in the constructor since it's usually only done to store that in properties. I invite you to read the links I posted if not already done, this is interesting.

**Comment by felixfbecker** [comment]
@mnapoli thanks for all the info, definitely makes sense.
