### ISSUE TITLE
Problem when register new service

### ISSUE THREAD

**Issue by minhtkh** [PHP-DI/Silex-Bridge#3]
I try to register services using DI-Bridge for Silex
it work find for some services like Twig or Doctrine
but it has error when I register SwiftmailerServiceProvider

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Service definition is not a Closure or invokable object.' in /vendor/pimple/pimple/lib/Pimple.php:119 
Stack trace: 
#0 /vagrant/vendor/silex/silex/src/Silex/Application.php(317): Pimple::share(NULL) 
#1 /vendor/silex/silex/src/Silex/Application.php(388): Silex\Application->on('kernel.terminat...', Object(Closure), 0) 
#2 /vendor/silex/silex/src/Silex/Provider/SwiftmailerServiceProvider.php(97): Silex\Application->finish(Object(Closure)) 
#3 /vendor/silex/silex/src/Silex/Application.php(192): Silex\Provider\SwiftmailerServiceProvider->boot(Object(DI\Bridge\Silex\Application)) 
#4 /vendor/silex/silex/src/Silex/Application.php(577): Silex\Application->boot() 
#5 /vendor/silex/silex/src/Silex/Application.php(563): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#6 /public/me in /vendor/pimple/pimple/lib/Pimple.php on line 119
```

anyone has any idea ?

**Comment by mnapoli** [comment]
Please provide some code to understand what you did.

**Comment by minhtkh** [comment]
```
$builder = new DI\ContainerBuilder();
$builder->addDefinitions(__DIR__. '/../config/config.php');
$app = new DI\Bridge\Silex\Application($builder);
$app['debug'] = true;
// Twig template
$app->register(new Silex\Provider\TwigServiceProvider(), array(
    'twig.path' => __DIR__.'/../resources/views',
));
// Doctrine
$app->register(new Silex\Provider\DoctrineServiceProvider, array(
    "db.options" => array(
        "driver" => "pdo_sqlite",
        "path" => __DIR__ . "/../storage/database/tests.sqlite3",
    ),
));
$app->register(new Dflydev\Silex\Provider\DoctrineOrm\DoctrineOrmServiceProvider, array(
    // "orm.proxies_dir" => "/path/to/proxies",
    "orm.em.options" => array(
        "mappings" => array(
            array(
                "type" => "simple_yml",
                "namespace" => "App\Entity",
                "path" => __DIR__."/../databases/mappings",
            ),
        ),
    ),
));
// Silex Session Service Provider
$app->register(new Silex\Provider\SessionServiceProvider());
// Mail Provider
$app->register(new Silex\Provider\SwiftmailerServiceProvider(), array(
    'swiftmailer.options' => array(
        'host' => 'smtp.gmail.com',
        'port' => 465,
        'username' => 'silex.swiftmailer@gmail.com',
        'password' => 'simplepassword',
        'encryption' => 'ssl',
        'auth_mode' => 'login'
    )
));
$app->register(new Silex\Provider\UrlGeneratorServiceProvider());
```

I just follow documentation
Moreover, I also have problem with UrlGeneratorServiceProvider, it prints out error

```
Fatal error: Call to undefined method Interop\Container\Pimple\PimpleInterop::flush() in /vendor/silex/silex/src/Silex/Provider/UrlGeneratorServiceProvider.php on line 30
```

and here is class UrlGeneratorServiceProvider

```
namespace Silex\Provider;

use Silex\Application;
use Silex\ServiceProviderInterface;
use Symfony\Component\Routing\Generator\UrlGenerator;

class UrlGeneratorServiceProvider implements ServiceProviderInterface
{
    public function register(Application $app)
    {
        $app['url_generator'] = $app->share(function ($app) {
            $app->flush();
            return new UrlGenerator($app['routes'], $app['request_context']);
        });
    }

    public function boot(Application $app)
    {
    }
}
```

the $app here is DI\Bridge\Silex\Application, which extends \Silex\Application, I don't know why it doesn't have flush() method

**Comment by mnapoli** [comment]
OK I think both bugs come back to the same root issue: the application extends Pimple but this container isn't used.

Here are all the containers in the app:
- Application extends Pimple (unused)
- composite container
  - Pimple (actually it's PimpleInterop)
  - PHP-DI

Symptom 1: `$this->extend()` written in the application (e.g. [the event dispatcher](https://github.com/silexphp/Pimple/blob/1.1/lib/Pimple.php#L198-L202)) will extend an entry from the "Application extends Pimple" container. It should instead extend entries from the "PimpleInterop" container.

-> that's your first issue with `SwiftmailerServiceProvider` (which uses events).

Symptom 2: `$app->share(function ($app) {…` In this, `$app` will not be the application, but it will be the `PimpleInterop` container instead. So that's why calling methods of the application do not work.

-> that's your second issue with `UrlGeneratorServiceProvider`.

---

Solutions?
- use the "Application extends Pimple" container directly => it's a problem since it means we can't integrate PHP-DI in there (that's why it wasn't done this way). I don't think it's doable.
- forward `extend()` to the PimpleInterop container so that it will work correctly
  - will fix Symptom 1
- forward `PimpleInterop::*()` method calls to `Application::*()` if it's not a Pimple method
  - will fix Symptom 2 by allowing to call Application methods when using the container.

I'll look into implementing that. Thanks for the report!

Note to self: gaaaaahhhh Silex and Pimple are a mess! :)

**Comment by mnapoli** [comment]
A precision:

> - forward `extend()` to the PimpleInterop container so that it will work correctly

It turns out it's already the case. I'm having trouble reproducing your first problem. I'll start by fixing the second issue and look into the first one later.

**Comment by minhtkh** [comment]
thank you so much, waiting for your update, hopefully it will be OK whenever using a service in Silex + PHP-DI

**Comment by mnapoli** [comment]
I've done a big refactoring in #4. It seems to be turning out really great, the whole thing is much much simpler, with less composer dependencies and objects. Also I have added tests for more service providers (those that you were having issues with) to make sure that they work.

I'll be merging #4 and creating a new release straight away so that you can test.

**Comment by mnapoli** [comment]
The issue was closed by GitHub when merging the pull request, we'll reopen it if that's not fixed for you.

Could you try upgrading to the new `1.2.0` version and tell me if it works? (you might have to wait ~5 minutes before Packagist detects the new version)

**Comment by minhtkh** [comment]
yeah, it works perfectly now, thank you so much

**Comment by mnapoli** [comment]
Thanks for letting me know!
