### ISSUE TITLE
Silex v2 compatibility

### ISSUE THREAD

**Issue by silverpark** [PHP-DI/Silex-Bridge#6]
Hi,

Could you make branch compatible with silex dev-master branch ? Because I can't use Silex-Bridge with her dependencies.

Regards,

**Comment by mnapoli** [comment]
Hi, @jdreesen has been working on it, see #5. @jdreesen maybe we could merge your change in a `v2` branch as you offered since others are interested too? Is your fork stable?

**Comment by jdreesen** [comment]
I hadn't had the time to test it further yet. But I don't think that there's much space for errors because the PHP-DI Silex bridge is rather small and there aren't that much BC breaks.

Anyway, because of the API incompatibilities,I'd like to change the composer version constraints to only support Silex 2 / Pimple 3 and not both versions in that branch, first.

**Comment by jdreesen** [comment]
Oh, and the tests are failing at the moment because of a bug in Silex 2 which requires the Symfony Twig bridge to be available, which we don't have. See: https://github.com/silexphp/Silex/pull/1245

**Comment by ricardokenji** [comment]
Is it still in the works? I forked silex-bridge master, changed composer require to silex 2@dev and pimple to 3.0 and it is working, at least i'm not getting any error and dependencies are being autowired corretly.

**Comment by mnapoli** [comment]
@ricardokenji there is no ongoing work right now that I know of, feel free to submit a pull request if you find a way to make this bridge work with Silex 1 & 2?

**Comment by jdreesen** [comment]
It can't be working out of the box because Pimple 3 has no `share()` method which is used in the constructor of this bridge's `Application` class. Also there are some other small problems and several tests are failing when simply doing a composer update to Silex 2/Pimple 3.

As Silex 2 final wasn't released yet and I haven't had enough time for my project that uses Silex 2 in the last months, there's no progress from my side on this for now.

**Comment by ricardokenji** [comment]
Yeah, i forgot i made some changes, but making  changes like $app->share() to a simple closure , which i believe is the new way to make a shareable instance, and some other changes fixes all tests. I am new to silex and didnt had time to check everything tho.

**Comment by jdreesen** [comment]
Yes, services in Pimple 3 are shared by default so `share()` is not necessary anymore.

I quickly created #11 some minutes ago which should make this bridge compatible with Silex 1 and 2 at the same time. But as I'm not using either version of silex at the moment it may be that I forgot something ;)

**Comment by mnapoli** [comment]
Update: I've created a `silex-2` branch from master. Feel free to send pull requests for that branch if you want support before the stable release of Silex 2.

**Comment by ricardokenji** [comment]
Guess i will wait jrdreesen, no point two people doing the same thing.

**Comment by praswicaksono** [comment]
Yup so @jdreesen would you like PR initial support for silex 2?

**Comment by jdreesen** [comment]
Sure, I just submitted the PR. It would be nice if you could have a look if everything's fine :)

**Comment by jdreesen** [comment]
Silex 2 [has just](https://twitter.com/fabpot/status/732848312819318784) [been released](https://github.com/silexphp/Silex/releases/tag/v2.0.0)! :tada: 
I'll have a look if something has to be done to make this bridge compatible later today or the next days.

**Comment by mnapoli** [comment]
Great news!

**Comment by jdreesen** [comment]
I just pushed a first version of the needed changes in #17

**Comment by mnapoli** [comment]
Silex 2 support was implemented by @jdreesen in #17! v2.0.0-beta1 has been tagged: https://github.com/PHP-DI/Silex-Bridge/releases/tag/2.0.0-beta1 Please try it out and report any issues you may have so that we can work it out for the stable release.
